name: first workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print welcome
        run: echo "welcome reem"
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: list file
        run: ls -la
